$ANSIBLE_VAULT;1.1;AES256
36376538613238376138653164376139323563313336316134326564643730616363666137663134
6631653061626234343262376333643365363965393336300a333736613935303535656134653730
62353839396561313964346330373736656632383763626661343332363564643830303131303965
6463336634616363370a333032343330626330346530643064376137336566373335376134613463
37336665336264386162633263303335333462363231646532666135326536656261626239366434
65343632393765626133373266373337326433303364383562366439636234373864316137353766
65336431666162666431393533313262646564323065653036343963633866373363643838666234
36386663373262393138343764366235633039313436656637363463346663366464336538656631
3835
