$ANSIBLE_VAULT;1.1;AES256
62383438316534353236616662616131653565613037363339623131313762336462393837333364
3538313261626430323466656635636462336366643565620a393635656538346163356466383939
34383566316261353032383839316561616631623634653839396562656165376566653064353734
3131346465656133330a326434343139343337326438373836343739626662363563323630663239
34643763616366396431623334396438383963636530353236653037623663656438393132376534
62666233633237366565336134313566393930353030386537646431643931663864333966623738
66386233333236633265663535343135346262666439656631626265353334363138643663373039
63623531366362343137616639313630393365616361633361333932323465383033613130333731
37626361636166626631363533326266396366313436393833326130346563366235
